"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t7$pm^d9tz!^a34u+da%69v^z=w2#evbw86gy$)f4&@)jf9rwh'
GOOGLE_CLIENT_SECRET = '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'
CLIENT_ID = '1041474063844-oiacl9hvlhgngnf859fsuchnl41cfs96.apps.googleusercontent.com'

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': '1041474063844-oiacl9hvlhgngnf859fsuchnl41cfs96.apps.googleusercontent.com',
            'secret': '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',
            'key': ''
        }
    }
}


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['https://eduway-back-end.onrender.com','127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Для allauth

    # Django REST Framework + Auth
    'rest_framework',
    'rest_framework.authtoken',  # Нужно для dj-rest-auth
    'dj_rest_auth',
    'dj_rest_auth.registration',

    # Allauth (Google OAuth)
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    # Твоё кастомное приложение (если у тебя есть `users` для кастомного пользователя)
    'users',
]  


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'allauth.account.middleware.AccountMiddleware', 
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'my_database',
        'USER': 'your_db_user',
        'PASSWORD': 'ArtuR',
        'HOST': 'localhost',  # или IP сервера PostgreSQL
        'PORT': '5432',  # стандартный порт PostgreSQL
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SITE_ID = 1
# Настройки Django Allauth и Dj-Rest-Auth
REST_USE_JWT = True

ACCOUNT_LOGIN_METHODS = {"email"} # Вход только по email
ACCOUNT_EMAIL_REQUIRED = True  # Email обязателен
ACCOUNT_USERNAME_REQUIRED = False  # Не требуем username
ACCOUNT_USER_MODEL_USERNAME_FIELD = None  # Отключаем username
ACCOUNT_EMAIL_VERIFICATION = "optional"  # Или 'mandatory', если хочешь подтверждение email


